# Generated by Django 4.0.2 on 2024-07-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profession',
            options={'verbose_name': 'Профессия', 'verbose_name_plural': 'Профессии'},
        ),
        migrations.AlterModelOptions(
            name='stars',
            options={'verbose_name': 'Звезда', 'verbose_name_plural': 'Звезды'},
        ),
        migrations.AddField(
            model_name='stars',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
